### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by huyquangtranaus** [albertotb/get-gfs#1]
Hi @albertotb ,

Could you please advice what I should do to combat the error message below?

Thanks

(py2) C:\get-gfs-master>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libedit==3.1.20181209=hc058e9b_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - sqlite==3.28.0=h7b6447c_0
  - intel-openmp==2019.4=243
  - readline==7.0=h7b6447c_5
  - python==2.7.16=h9bab390_0
  - mkl==2019.4=243
  - ncurses==6.1=he6710b0_1
  - zlib==1.2.11=h7b6447c_3
  - mkl_random==1.0.2=py27hd81dba3_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - numpy-base==1.16.4=py27hde5b4d6_0
  - pandas==0.24.2=py27he6710b0_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libffi==3.2.1=hd88cf55_4
  - tk==8.6.8=hbc83047_0
  - openssl==1.1.1c=h7b6447c_1
  - numpy==1.16.4=py27h7e9f1db_0
  - mkl_fft==1.0.12=py27ha843d7b_0

**Comment by albertotb** [comment]
I just update the `environment.yml`. Please try to create the environment now. Also issue the command from base environment (no py2 in prompt).

**Comment by huyquangtranaus** [comment]
Thank you Alberto,

Sorry for a late reply due to time lag..

What do you mean "no py2 in prompt?"

Indeed, I mainly use Anaconda 3+, but as mentioned in here, your code works only Python 2.7+, so I switched to this version by activating:  activate py2 in Windows.

The error message now  is below. What should I do? Thanks:

(py2) C:\get-gfs-master>conda env create -f environment.yml python=2.7
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - pip=19.1.1 -> python[version='>=3.6,<3.7.0a0']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you've asked for.
Your current python version is (python=2.7).

The following specifications were found to be incompatible with each other:

  - numpy=1.16.4 -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1b,<1.1.2a'] -> vc[version='>=14.1,<15.0a0']
  - pandas=0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1b,<1.1.2a'] -> vc[version='>=14.1,<15.0a0']
  - pip=19.1.1 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> vc[version='>=14.1,<15.0a0']
  - python=2.7 -> sqlite[version='>=3.27.2,<4.0a0'] -> vc[version='>=14.1,<15.0a0']
  - requests -> certifi[version='>=2017.4.17'] -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='>=3.27.2,<4.0a0'] -> vc[version='>=14.1,<15.0a0']




(py2) C:\get-gfs-master>python --version
Python 2.7.16 :: Anaconda, Inc.

(py2) C:\get-gfs-master>conda env create -f environment.yml python=2.7.16
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - pip=19.1.1 -> python[version='>=3.6,<3.7.0a0']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you've asked for.
Your current python version is (python=2.7).

The following specifications were found to be incompatible with each other:

  - numpy=1.16.4 -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1b,<1.1.2a'] -> vc[version='>=14.1,<15.0a0']
  - pandas=0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1b,<1.1.2a'] -> vc[version='>=14.1,<15.0a0']
  - pip=19.1.1 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> vc[version='>=14.1,<15.0a0']
  - python=2.7 -> sqlite[version='>=3.27.2,<4.0a0'] -> vc[version='>=14.1,<15.0a0']
  - requests -> certifi[version='>=2017.4.17'] -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='>=3.27.2,<4.0a0'] -> vc[version='>=14.1,<15.0a0']




(py2) C:\get-gfs-master>

**Comment by albertotb** [comment]
I mean that you do not have to do `conda activate py2` first, the
environment.yml already installs an environment with Python 2. Try that and
if it does not work I will take a look at the versions in the
`environment.yml` file

**Comment by huyquangtranaus** [comment]
Thanks for quick reply @albertotb ,

but it is still not working.. here is the new error message:

C:\get-gfs-master>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package python conflicts for:
pip=19.1.1 -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
python=2.7
pandas=0.24.2 -> numpy[version='>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
numpy=1.16.4 -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
Package setuptools conflicts for:
pip=19.1.1 -> wheel -> setuptools
python=2.7 -> pip -> wheel -> setuptools
pandas=0.24.2 -> numpy[version='>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
numpy=1.16.4 -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools
Package wheel conflicts for:
requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
pandas=0.24.2 -> numpy[version='>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
python=2.7 -> pip -> wheel
numpy=1.16.4 -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
pip=19.1.1 -> wheel
Package wincertstore conflicts for:
pip=19.1.1 -> wheel -> setuptools -> wincertstore[version='>=0.2']
pandas=0.24.2 -> numpy[version='>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools -> wincertstore[version='>=0.2']
requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools -> wincertstore[version='>=0.2']
numpy=1.16.4 -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools -> wincertstore[version='>=0.2']
python=2.7 -> pip -> wheel -> setuptools -> wincertstore[version='>=0.2']
Package certifi conflicts for:
pandas=0.24.2 -> numpy[version='>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> certifi
python=2.7 -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> certifi
numpy=1.16.4 -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> certifi
pip=19.1.1 -> certifi
requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
Package pip conflicts for:
pandas=0.24.2 -> numpy[version='>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
numpy=1.16.4 -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
python=2.7 -> pip
pip=19.1.1
requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
Package vc conflicts for:
pandas=0.24.2 -> numpy[version='>=1.12.1,<2.0a0,>=1.14.6,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> cffi[version='>=1.7'] -> vc[version='14.*,9.*,>=14.1,<15.0a0']
numpy=1.16.4 -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> python[version='>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> cffi[version='>=1.7'] -> vc[version='14.*,>=14.1,<15.0a0']
requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> six[version='>=1.4.1'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> cachecontrol -> msgpack-python -> vc=9
pip=19.1.1 -> python[version='>=2.7,<2.8.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> sqlite[version='>=3.26.0,<4.0a0'] -> vc=9
python=2.7 -> pip -> cachecontrol -> requests -> urllib3[version='>=1.21.1,<1.23,>=1.21.1,<1.24,>=1.21.1,<1.25'] -> pyopenssl[version='>=0.14'] -> cryptography[version='>=1.9,>=2.1.4,>=2.2.1'] -> cffi[version='>=1.7'] -> vc=9


C:\get-gfs-master>

**Comment by albertotb** [comment]
I just updated the environment.yml file, try with this one. Please make
sure to remove first the get-gfs environment as to avoid conflicts with

`conda remove --name get-gfs --all`

If it is still not working, the dependency list is quite small. Just
activate your py2 environment and install:

`conda install numpy pandas requests`
`pip install pydap`

**Comment by huyquangtranaus** [comment]
Great thanks... I can activate it by new environment, but now I would like to test if every is working perfectly... 

Can you give me an example for the command to download GFS? e.g. wind 10m (U,V) for the entire world, 0.25 degree  for tomorrow?

**Comment by albertotb** [comment]
I just added an example to the README. For the whole world just adjust the lat and lon coordinates. If you only want u and v at 10m remove the other lines from the file `example_conf.json`.

**Comment by huyquangtranaus** [comment]
Great @albertotb , but :(

(get-gfs) C:\get-gfs-master>python get_gfs.py -s 1 -r 0.25 -t 0 48 -x -10 10 -y -15 15 -p 0 2 -c example_conf.json 20190730 00
Traceback (most recent call last):
  File "get_gfs.py", line 247, in <module>
    sys.exit(main(sys.argv))
  File "get_gfs.py", line 211, in main
    var_conf = json.load(f)
NameError: name 'json' is not defined

**Comment by albertotb** [comment]
You have to download the new version, I updateed `get_gfs.py`

**Comment by huyquangtranaus** [comment]
It is still not working bro,

the error as a screenshot is attached.
![gfs_error](https://user-images.githubusercontent.com/32722297/62183587-20eb3180-b39e-11e9-9b72-1d0c30dd503e.png)

**Comment by albertotb** [comment]
The example is working for me right now. That error indicates that the file
is not present on the server, maybe you cannot access it? Another
possibility is that the server was down just the moment you run the query.
What happens if you copy that url in the browser?

**Comment by huyquangtranaus** [comment]
For me it is still not working :(
Below is the message after I copy the link:
https://nomads.ncep.noaa.gov:9090/dods/gfs_{res}{step}/gfs{date}/gfs_{res}{step}_{hour:02d}z.dods?
in the browser:

Error {
    code = 0;
    message = "subset requests must include a constraint expression";
};

**Comment by albertotb** [comment]
Not that url, the one that you had selected in your red box. I just added a
new version. Run with the -v flag to see the requests being made to the
server.

If you paste one in the browser, for instance

https://nomads.ncep.noaa.gov:9090/dods/gfs_0p25_1hr/gfs20190730/gfs_0p25_1hr_00z.dods?lat,lon

and it works, the program should also work. If the program doesn't work,
you probably have some network error or something is killing your process.
You can see the output in the browser replacing ".dods" with ".ascii" like
this

https://nomads.ncep.noaa.gov:9090/dods/gfs_0p25_1hr/gfs20190730/gfs_0p25_1hr_00z.ascii?lat,lon

**Comment by huyquangtranaus** [comment]
Ok.. It works on my linux now. I still don't know why I got error on Windows system. 

By the way, how do you plot data? can you make another version to work with GFS-NetCF file at here:
https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/

**Comment by albertotb** [comment]
For plotting please refer to https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html The program just downloads a regular CSV that you can load in Pandas for plotting or in any other software, like R. 

I don’t know which model is in 
https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/

I would need the documentation. Please open another issue with more details about the new features you want. I will close this one since the env issue is solved.
